### Numpy Continuation:

### Random method:

In [1]:
import numpy as np

In [5]:
np.random.randint(100)   ### generating single integer value within the defined range.

52

In [7]:
np.random.rand()  ### generating float value within the range 0 and 1

0.540091072653877

In [8]:
np.random.randint(10,100,size = (10))   ### 1-d array

array([93, 32, 79, 74, 74, 34, 20, 49, 22, 31])

In [9]:
np.random.randint(10,100,size = (3,4))  ### 2-d array

array([[77, 94, 56, 93],
       [10, 43, 95, 27],
       [58, 30, 60, 33]])

In [10]:
np.random.randint(10,100,size = (2,3,4))  ###3-d array

array([[[90, 19, 65, 36],
        [42, 83, 76, 88],
        [92, 42, 41, 68]],

       [[16, 22, 53, 68],
        [20, 87, 84, 84],
        [22, 92, 40, 54]]])

In [11]:
np.random.randint(10,100,size = (2,2,2,3,4))

array([[[[[56, 76, 62, 73],
          [53, 27, 48, 31],
          [53, 95, 78, 51]],

         [[97, 71, 11, 67],
          [27, 35, 61, 34],
          [28, 90, 26, 15]]],


        [[[33, 59, 67, 91],
          [68, 55, 97, 89],
          [13, 88, 46, 92]],

         [[67, 91, 60, 47],
          [92, 39, 63, 21],
          [31, 59, 92, 81]]]],



       [[[[86, 20, 85, 74],
          [87, 18, 86, 88],
          [44, 88, 60, 81]],

         [[48, 60, 58, 57],
          [64, 94, 81, 34],
          [43, 37, 77, 63]]],


        [[[58, 89, 89, 16],
          [16, 42, 37, 59],
          [59, 16, 33, 17]],

         [[78, 54, 27, 14],
          [66, 80, 29, 91],
          [70, 60, 30, 28]]]]])

In [18]:
np.random.choice([10,12,9,100,3])   ## choice of numbers

12

In [19]:
np.random.choice([10,12,9,100,3],size = (3,3))

array([[ 10,   3,   3],
       [ 10, 100,   9],
       [ 12,   9,   3]])

In [32]:
np.random.choice([10,12,9,100,3],p=[0.6,0,0.1,0.2,0.1])

10

In [33]:
np.random.choice([10,12,9,100,3],p=[0.6,0,0.1,0.2,0.1],size = (3,3))

array([[100, 100,  10],
       [100,  10,   3],
       [ 10,  10,   3]])

In [47]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
np.random.shuffle(a)
a

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [50]:
np.random.randn(10)  ### positive as well as negatives values.

array([-1.01001158,  0.04852173, -0.53393765,  0.17011892,  1.81268173,
       -1.01617254,  1.48649225, -0.10184327, -0.11377124,  0.64054585])

In [55]:
np.random.binomial(10,p=[0.1])

array([0])

In [61]:
np.random.normal()

0.5819330480765686

### Array Filtering:

In [62]:
a = np.array([1,10,45,70,90,100,2,34])
a

array([  1,  10,  45,  70,  90, 100,   2,  34])

In [63]:
b = [True,False,True,False,True,True,False,False]
c = a[b]
c

array([  1,  45,  90, 100])

In [64]:
### create an array with elements greater than 15.
b = []
for i in a:
    if i > 15:
        b.append(True)
    else:
        b.append(False)

c = a[b]

c


array([ 45,  70,  90, 100,  34])

In [65]:
d = a[a>15]

In [66]:
d

array([ 45,  70,  90, 100,  34])

In [67]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
b = a

In [69]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.dot(a,b)   ### dot product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [73]:
a.T   ### Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Pandas

In [74]:
### installation:


In [75]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [76]:
### importing:

import pandas as pd

In [77]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [78]:
len(dir(pd))

139

In [79]:
### version check:

pd.__version__

'0.24.2'

### Series:

* The data is in the format of 1-d.
* The output is in the format of row wise.

In [80]:
### creating the data using series:

a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [81]:
### Creating data using numpy in Series format:

import numpy as np
a = pd.Series(np.array([4,5,6,8]))
a

0    4
1    5
2    6
3    8
dtype: int32

In [84]:
### creating series using tuple:

a = pd.Series((1,2,3,5))
a

0    1
1    2
2    3
3    5
dtype: int64

In [85]:
### creating series using Dictionary:

d = {'a':1,'b':2,'c':3}
d

{'a': 1, 'b': 2, 'c': 3}

In [86]:
a = pd.Series(d)
a

a    1
b    2
c    3
dtype: int64

In [87]:
a = pd.Series([1,2,3,4],index = ['s','e','r','i'])
a

s    1
e    2
r    3
i    4
dtype: int64

In [94]:
a = [1,2,3,4,5,'a']
b = pd.Series(a,index = np.arange(1,len(a)+1))
b

1    1
2    2
3    3
4    4
5    5
6    a
dtype: object

In [95]:
b.dtype

dtype('O')

### DataFrames:

In [96]:
a = pd.DataFrame([1,2,3,4])
a

0
0  1
1  2
2  3
3  4

In [97]:
### creating multiple columns:

a = pd.DataFrame([["abc",30,2],["dcb",40,4],["exc",56,14]])
a

0   1   2
0  abc  30   2
1  dcb  40   4
2  exc  56  14

In [98]:
a = pd.DataFrame([["abc",30,2],["dcb",40,4],["exc",56,14]],columns = ["Name","year","Number"])
a

Name  year  Number
0  abc    30       2
1  dcb    40       4
2  exc    56      14

In [99]:
a.index = [1,2,3]

In [100]:
a

Name  year  Number
1  abc    30       2
2  dcb    40       4
3  exc    56      14

In [101]:
d = {"Name":["Niharikaa","Mounica","Lavnaya"],
    "year":[2018,2019,2017],
    "batch":[2,3,4]}
d

{'Name': ['Niharikaa', 'Mounica', 'Lavnaya'],
 'year': [2018, 2019, 2017],
 'batch': [2, 3, 4]}

In [102]:
a = pd.DataFrame(d,index = [1,2,3])

In [103]:
a

Name  year  batch
1  Niharikaa  2018      2
2    Mounica  2019      3
3    Lavnaya  2017      4

In [105]:
### creating dataframes using mutliple dictonaries:

data = [{'a' : 1,"b":2,"c":3},
       {'a':3,"b":5,"c":6}]
a = pd.DataFrame(data)
a

a  b  c
0  1  2  3
1  3  5  6

In [106]:
data = [{'a' : 1,"b":2,"c":3},
       {'a':3,"b":5,"c":6,"d":7}]
a = pd.DataFrame(data)
a

a  b  c    d
0  1  2  3  NaN
1  3  5  6  7.0

In [107]:
a.index=['a','b']

In [108]:
a

a  b  c    d
a  1  2  3  NaN
b  3  5  6  7.0

In [109]:
### converting Series into Dataframe:

d = {"one":pd.Series([1,2,3]),
    "Two":pd.Series([4,5,7]),
    "Three":pd.Series([8,9])}
a = pd.DataFrame(d)
a

one  Two  Three
0    1    4    8.0
1    2    5    9.0
2    3    7    NaN

In [110]:
a = pd.DataFrame(d,dtype = float)

In [111]:
a

one  Two  Three
0  1.0  4.0    8.0
1  2.0  5.0    9.0
2  3.0  7.0    NaN

In [112]:
a = pd.DataFrame(d,dtype = complex)

In [113]:
a

one     Two   Three
0  (1+0j)  (4+0j)  (8+0j)
1  (2+0j)  (5+0j)  (9+0j)
2  (3+0j)  (7+0j)     NaN

### slicing and Indexing :

In [116]:
### series indexing:

s2 = pd.Series([12,34,5665,24,67,78.45])
s2

0      12.00
1      34.00
2    5665.00
3      24.00
4      67.00
5      78.45
dtype: float64

In [117]:
s2.index = ["a","b",3,"r",5,6]
s2

a      12.00
b      34.00
3    5665.00
r      24.00
5      67.00
6      78.45
dtype: float64

In [118]:
s2[5]

67.0

In [119]:
s2[3:5]   ## implict indexing

r    24.0
5    67.0
dtype: float64

In [120]:
s2["a":"r"]  ### explict indexing

a      12.0
b      34.0
3    5665.0
r      24.0
dtype: float64

In [121]:
s2[:4]

a      12.0
b      34.0
3    5665.0
r      24.0
dtype: float64

In [123]:
s2[-2:]

5    67.00
6    78.45
dtype: float64

In [124]:
s2

a      12.00
b      34.00
3    5665.00
r      24.00
5      67.00
6      78.45
dtype: float64

In [126]:
### fancy slicing

s2[['a','r',6]]

a    12.00
r    24.00
6    78.45
dtype: float64

In [127]:
### Data Frames:

d = {"one":pd.Series([1,2,3]),
    "Two":pd.Series([4,5,7]),
    "Three":pd.Series([8,9,10])}
a = pd.DataFrame(d)
a

one  Two  Three
0    1    4      8
1    2    5      9
2    3    7     10

In [128]:
a.values

array([[ 1,  4,  8],
       [ 2,  5,  9],
       [ 3,  7, 10]], dtype=int64)

In [129]:
a.index

RangeIndex(start=0, stop=3, step=1)

In [130]:
a["one"]

0    1
1    2
2    3
Name: one, dtype: int64

In [131]:
a["one"][2]

3

In [132]:
a[-1:]

one  Two  Three
2    3    7     10

In [134]:
a[1:]

one  Two  Three
1    2    5      9
2    3    7     10

In [137]:
a.head(1)

one  Two  Three
0    1    4      8

In [138]:
a.tail(1)

one  Two  Three
2    3    7     10

In [139]:
a.columns

Index(['one', 'Two', 'Three'], dtype='object')

### iloc and loc:

In [141]:
a = pd.DataFrame([[1,2,3,4,5],[5,6,7,9,10]],columns = ["python","c","java","a","b"],index = [1,'a'])
a

python  c  java  a   b
1       1  2     3  4   5
a       5  6     7  9  10

In [143]:
a.loc['a']

python     5
c          6
java       7
a          9
b         10
Name: a, dtype: int64

In [144]:
a.iloc[1]

python     5
c          6
java       7
a          9
b         10
Name: a, dtype: int64

In [146]:
a.iloc[1]

python     5
c          6
java       7
a          9
b         10
Name: a, dtype: int64

In [147]:
a.loc['a']

python     5
c          6
java       7
a          9
b         10
Name: a, dtype: int64

In [148]:
a.iloc[0]

python    1
c         2
java      3
a         4
b         5
Name: 1, dtype: int64

In [153]:
a.iloc[1][-1]

10

In [151]:
a

python  c  java  a   b
1       1  2     3  4   5
a       5  6     7  9  10

### Date range/Series

In [155]:
s = pd.date_range(start = "2020-11-27",end = "2020-12-05")
s

DatetimeIndex(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
               '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04',
               '2020-12-05'],
              dtype='datetime64[ns]', freq='D')

In [156]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs)
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : integer, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/end dates to midnight before generating dat

In [162]:
pd.date_range(start='2018-04-24', end='2018-04-27', periods=3)

DatetimeIndex(['2018-04-24 00:00:00', '2018-04-25 12:00:00',
               '2018-04-27 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [163]:
pd.date_range(start='1/1/2018', periods=5, freq='M')

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31'],
              dtype='datetime64[ns]', freq='M')

In [164]:
pd.date_range(start='1/1/2018', periods=5, freq='3M')

DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
               '2019-01-31'],
              dtype='datetime64[ns]', freq='3M')

In [165]:
a

python  c  java  a   b
1       1  2     3  4   5
a       5  6     7  9  10

In [169]:
del a["c"]   ### deleting a particular column from the dataframe.

In [170]:
a

python  a   b
1       1  4   5
a       5  9  10

In [171]:
a.isnull()

python      a      b
1   False  False  False
a   False  False  False

In [172]:
a.notnull()

python     a     b
1    True  True  True
a    True  True  True

### combining and merging of dataframes:


In [174]:
a = {"name":["niharikaa","mounika","lavanya"],
    "Branch":["Ece","cse","ece"],
    "Gender":["F","F","F"]}
a = pd.DataFrame(a,index = [121,122,123])

In [175]:
a

name Branch Gender
121  niharikaa    Ece      F
122    mounika    cse      F
123    lavanya    ece      F

In [178]:
pd.concat([a,a])  ### rows concate

name Branch Gender
121  niharikaa    Ece      F
122    mounika    cse      F
123    lavanya    ece      F
121  niharikaa    Ece      F
122    mounika    cse      F
123    lavanya    ece      F

In [180]:
pd.concat([a,a],axis = 1)  ### column concate

name Branch Gender       name Branch Gender
121  niharikaa    Ece      F  niharikaa    Ece      F
122    mounika    cse      F    mounika    cse      F
123    lavanya    ece      F    lavanya    ece      F

In [182]:
a.append(a)  ### only wise appending

name Branch Gender
121  niharikaa    Ece      F
122    mounika    cse      F
123    lavanya    ece      F
121  niharikaa    Ece      F
122    mounika    cse      F
123    lavanya    ece      F

In [183]:
pd.merge(a,a)

name Branch Gender
0  niharikaa    Ece      F
1    mounika    cse      F
2    lavanya    ece      F

In [184]:
d1 = pd.DataFrame({"std_name":['r','b','v','t'],
                  "age":[6,7,8,2]})
d1

std_name  age
0        r    6
1        b    7
2        v    8
3        t    2

In [185]:
d2 = pd.DataFrame({"std_name":['r','a','b','z'],
                  "fav_fruit":["mango","banana","apple","grapes"]})
d2

std_name fav_fruit
0        r     mango
1        a    banana
2        b     apple
3        z    grapes

In [186]:
pd.concat([d1,d2])

C:\Users\Niharikaa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


age fav_fruit std_name
0  6.0       NaN        r
1  7.0       NaN        b
2  8.0       NaN        v
3  2.0       NaN        t
0  NaN     mango        r
1  NaN    banana        a
2  NaN     apple        b
3  NaN    grapes        z

In [188]:
pd.merge(d1,d2)   ### common columns mmerging

std_name  age fav_fruit
0        r    6     mango
1        b    7     apple

In [190]:
pd.merge(d1,d2,how = "left")

std_name  age fav_fruit
0        r    6     mango
1        b    7     apple
2        v    8       NaN
3        t    2       NaN

In [191]:
pd.merge(d1,d2,how = "right")

std_name  age fav_fruit
0        r  6.0     mango
1        b  7.0     apple
2        a  NaN    banana
3        z  NaN    grapes

In [193]:
pd.merge(d1,d2,how = "outer")   ### union of both dataframes

std_name  age fav_fruit
0        r  6.0     mango
1        b  7.0     apple
2        v  8.0       NaN
3        t  2.0       NaN
4        a  NaN    banana
5        z  NaN    grapes

In [195]:
pd.merge(d1,d2,how = "inner")   ## intersection of both dataframes

std_name  age fav_fruit
0        r    6     mango
1        b    7     apple

In [196]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key 

### file reading:

In [197]:
data = pd.read_csv("https://raw.githubusercontent.com/APSSDC-Data-Analysis/Data-Analysis-batch8/main/Datasets/birds.csv")
data

id    huml   humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  \
0      0   80.78   6.68   72.01   4.88  41.81  3.70    5.50  4.03  38.70   
1      1   88.91   6.63   80.53   5.59  47.04  4.30   80.22  4.51  41.50   
2      2   79.97   6.37   69.26   5.28  43.07  3.90   75.35  4.04  38.31   
3      3   77.65   5.70   65.76   4.77  40.04  3.52   69.17  3.40  35.78   
4      4   62.80   4.84   52.09   3.73  33.95  2.72   56.27  2.96  31.88   
5      5   61.92   4.78   50.46   3.47  49.52  4.41   56.95  2.73  29.07   
6      6   79.73   5.94   67.39   4.50  42.07  3.41   71.26  3.56  37.22   
7      7   86.98   5.68   74.52   4.55  44.46  3.78   76.02  3.81  37.94   
8      8  118.20   7.82  116.64   6.13  59.33  5.45  110.00  5.58  61.62   
9      9  145.00  10.42  144.00   7.05  70.96  7.44  120.00  7.31  78.67   
10    10  165.00  11.45  156.00   8.68  80.25  7.85  143.00  8.25  86.61   
11    11  186.00   9.83  152.00   8.76  56.02  7.02  185.00  8.07  90.80   
12    12  172.00   8.44  142.00   8.43  52.18  6.68  180.00  9.62  82.58   
13    13  148.91   6.78  121.35   6.50  44.29  6.33  155.00  6.68  73.71   
14    14  149.19   6.98  121.48   6.21  43.33  5.39  155.00  6.61  75.65   
15    15  140.59   6.59  115.97   5.81  39.75  5.61  166.00  7.83  74.86   
16    16  135.23   6.22  108.78   5.83  37.99  5.13  157.00  7.18  72.44   
17    17  124.53   6.01  100.37   5.82  34.54  5.43  145.00  7.12  65.92   
18    18  127.03   6.18  102.53   5.64  36.52  4.89  150.00  6.78  67.27   
19    19  106.02   4.47   95.79   4.33  41.96  4.80  129.59  6.94  70.29   
20    20  113.84   4.80  100.71   4.39  43.95  5.08  133.27  7.41  70.91   
21    21  108.62   5.04   97.70   4.66  45.08  5.78  128.00  7.14  65.48   
22    22  110.33   5.86   97.10   4.60  43.82  5.73  126.00  7.86  64.17   
23    23   63.62   3.42   59.00   2.75  30.16  2.92   74.66  4.38  39.26   
24    24   70.73   3.69   65.19   2.93  32.52  3.54   80.42  4.36  43.70   
25    25   71.65   3.37   66.11   2.77  36.98  3.06   77.11  3.94  38.04   
26    26   47.51   7.23   32.49   8.26  50.29  5.00   75.20  4.95  22.51   
27    27   46.20   7.06   32.73   8.58  52.15  5.11   75.99  4.77  23.24   
28    28   41.13   6.71   31.00   7.73  49.51  4.69   71.94  4.54  22.46   
29    29   72.50  14.78   45.83  10.33  77.02  7.76  128.75  6.49  32.48   
..   ...     ...    ...     ...    ...    ...   ...     ...   ...    ...   
390  390   20.43   1.59   22.68   1.39  20.00  1.54   35.63  1.33  25.57   
391  391   22.19   1.86   24.93   1.52  24.14  1.78   40.17  1.73  29.61   
392  392   23.27   2.00   24.80   1.83  26.04  1.79   41.91  1.67  29.76   
393  393   18.97   1.58   21.26   1.40  21.50  1.55   36.52  1.52  25.04   
394  394   15.99   1.35   18.32   1.13  15.84  1.19   30.05  1.23  22.94   
395  395   15.62   1.28   18.52   1.06  15.75  1.17   28.63  1.03  21.39   
396  396   16.51   1.47   20.56   1.43  15.88  1.27     NaN  1.19  17.63   
397  397   16.80   1.58   19.77   1.39  16.86  1.29   29.75  1.18  21.77   
398  398   15.55   1.48   18.93   1.30  17.58  1.23   31.65  1.14  24.12   
399  399   23.32   2.06   27.90   1.84  22.49  1.66   34.77  1.42  23.05   
400  400   20.41   1.82   22.66   1.71  18.14  1.52   29.30  1.21  20.29   
401  401   21.53   1.91   25.30   1.67  20.80  1.65   34.08  1.33  23.86   
402  402   22.84   2.21   27.70   2.06  22.13  1.72   34.60  1.69  25.08   
403  403   20.95   1.89   24.12   1.66  21.24  1.84   36.71  1.53  25.99   
404  404   20.36   1.87   22.19   1.60    NaN  1.77   37.47  1.64  25.54   
405  405   17.30   1.68   20.43   1.33  15.51  1.15   25.96  0.88  17.41   
406  406   16.86   1.58   20.72   1.36  14.92  1.13   24.56  0.98  16.76   
407  407   15.70   1.42   18.58   1.20  15.22  1.08   25.39  0.92  16.88   
408  408   19.54   1.86   23.35   1.47  18.34  1.46   29.05  1.35  19.68   
409  409   23.27   2.15   27.62   2.16  21.86  1.64   35.55  1.51  23.23   
410  410   23.04   2.15   28.29   1.94  21.46  1.67   

In [198]:
data.head()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [199]:
data.tail()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  \
415  415  17.96  1.63  19.25   1.33  18.36  1.54  31.25  1.33  21.99  1.15   
416  416  19.21  1.64  20.76   1.49  19.24  1.45  33.21  1.28  23.60  1.15   
417  417  18.79  1.63  19.83   1.53  20.96  1.43  34.45  1.41  22.86  1.21   
418  418  20.38  1.78  22.53   1.50  21.35  1.48  36.09  1.53  25.98  1.24   
419  419  17.89  1.44  19.26   1.10  17.62  1.34  29.81  1.24  21.69  1.05   

    type  
415   SO  
416   SO  
417   SO  
418   SO  
419   SO

In [200]:
data.tail(3)

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  \
417  417  18.79  1.63  19.83   1.53  20.96  1.43  34.45  1.41  22.86  1.21   
418  418  20.38  1.78  22.53   1.50  21.35  1.48  36.09  1.53  25.98  1.24   
419  419  17.89  1.44  19.26   1.10  17.62  1.34  29.81  1.24  21.69  1.05   

    type  
417   SO  
418   SO  
419   SO

In [201]:
data = pd.read_csv("birds.csv")

In [202]:
data

id    huml   humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  \
0      0   80.78   6.68   72.01   4.88  41.81  3.70    5.50  4.03  38.70   
1      1   88.91   6.63   80.53   5.59  47.04  4.30   80.22  4.51  41.50   
2      2   79.97   6.37   69.26   5.28  43.07  3.90   75.35  4.04  38.31   
3      3   77.65   5.70   65.76   4.77  40.04  3.52   69.17  3.40  35.78   
4      4   62.80   4.84   52.09   3.73  33.95  2.72   56.27  2.96  31.88   
5      5   61.92   4.78   50.46   3.47  49.52  4.41   56.95  2.73  29.07   
6      6   79.73   5.94   67.39   4.50  42.07  3.41   71.26  3.56  37.22   
7      7   86.98   5.68   74.52   4.55  44.46  3.78   76.02  3.81  37.94   
8      8  118.20   7.82  116.64   6.13  59.33  5.45  110.00  5.58  61.62   
9      9  145.00  10.42  144.00   7.05  70.96  7.44  120.00  7.31  78.67   
10    10  165.00  11.45  156.00   8.68  80.25  7.85  143.00  8.25  86.61   
11    11  186.00   9.83  152.00   8.76  56.02  7.02  185.00  8.07  90.80   
12    12  172.00   8.44  142.00   8.43  52.18  6.68  180.00  9.62  82.58   
13    13  148.91   6.78  121.35   6.50  44.29  6.33  155.00  6.68  73.71   
14    14  149.19   6.98  121.48   6.21  43.33  5.39  155.00  6.61  75.65   
15    15  140.59   6.59  115.97   5.81  39.75  5.61  166.00  7.83  74.86   
16    16  135.23   6.22  108.78   5.83  37.99  5.13  157.00  7.18  72.44   
17    17  124.53   6.01  100.37   5.82  34.54  5.43  145.00  7.12  65.92   
18    18  127.03   6.18  102.53   5.64  36.52  4.89  150.00  6.78  67.27   
19    19  106.02   4.47   95.79   4.33  41.96  4.80  129.59  6.94  70.29   
20    20  113.84   4.80  100.71   4.39  43.95  5.08  133.27  7.41  70.91   
21    21  108.62   5.04   97.70   4.66  45.08  5.78  128.00  7.14  65.48   
22    22  110.33   5.86   97.10   4.60  43.82  5.73  126.00  7.86  64.17   
23    23   63.62   3.42   59.00   2.75  30.16  2.92   74.66  4.38  39.26   
24    24   70.73   3.69   65.19   2.93  32.52  3.54   80.42  4.36  43.70   
25    25   71.65   3.37   66.11   2.77  36.98  3.06   77.11  3.94  38.04   
26    26   47.51   7.23   32.49   8.26  50.29  5.00   75.20  4.95  22.51   
27    27   46.20   7.06   32.73   8.58  52.15  5.11   75.99  4.77  23.24   
28    28   41.13   6.71   31.00   7.73  49.51  4.69   71.94  4.54  22.46   
29    29   72.50  14.78   45.83  10.33  77.02  7.76  128.75  6.49  32.48   
..   ...     ...    ...     ...    ...    ...   ...     ...   ...    ...   
390  390   20.43   1.59   22.68   1.39  20.00  1.54   35.63  1.33  25.57   
391  391   22.19   1.86   24.93   1.52  24.14  1.78   40.17  1.73  29.61   
392  392   23.27   2.00   24.80   1.83  26.04  1.79   41.91  1.67  29.76   
393  393   18.97   1.58   21.26   1.40  21.50  1.55   36.52  1.52  25.04   
394  394   15.99   1.35   18.32   1.13  15.84  1.19   30.05  1.23  22.94   
395  395   15.62   1.28   18.52   1.06  15.75  1.17   28.63  1.03  21.39   
396  396   16.51   1.47   20.56   1.43  15.88  1.27     NaN  1.19  17.63   
397  397   16.80   1.58   19.77   1.39  16.86  1.29   29.75  1.18  21.77   
398  398   15.55   1.48   18.93   1.30  17.58  1.23   31.65  1.14  24.12   
399  399   23.32   2.06   27.90   1.84  22.49  1.66   34.77  1.42  23.05   
400  400   20.41   1.82   22.66   1.71  18.14  1.52   29.30  1.21  20.29   
401  401   21.53   1.91   25.30   1.67  20.80  1.65   34.08  1.33  23.86   
402  402   22.84   2.21   27.70   2.06  22.13  1.72   34.60  1.69  25.08   
403  403   20.95   1.89   24.12   1.66  21.24  1.84   36.71  1.53  25.99   
404  404   20.36   1.87   22.19   1.60    NaN  1.77   37.47  1.64  25.54   
405  405   17.30   1.68   20.43   1.33  15.51  1.15   25.96  0.88  17.41   
406  406   16.86   1.58   20.72   1.36  14.92  1.13   24.56  0.98  16.76   
407  407   15.70   1.42   18.58   1.20  15.22  1.08   25.39  0.92  16.88   
408  408   19.54   1.86   23.35   1.47  18.34  1.46   29.05  1.35  19.68   
409  409   23.27   2.15   27.62   2.16  21.86  1.64   35.55  1.51  23.23   
410  410   23.04   2.15   28.29   1.94  21.46  1.67   