### Numpy:

### Installation:



In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
### importing numpy:

import numpy as np

### Creating arrays with Different dimensions:

## 1-d array:

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a.dtype ### datatype of the array elements

dtype('int32')

In [10]:
a = np.array([1,2,3,4,'a'])

In [11]:
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [12]:
a = np.append(a,5)   ### adding a single element
a  

array(['1', '2', '3', '4', 'a', '5'], dtype='<U11')

In [13]:
a = np.append(a,[1,2,3,5,'n'])  ### adding list of elements

In [14]:
a

array(['1', '2', '3', '4', 'a', '5', '1', '2', '3', '5', 'n'],
      dtype='<U11')

In [15]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [18]:
a = np.arange(1,10,2)

In [19]:
a

array([1, 3, 5, 7, 9])

In [21]:
a.nbytes  ### memeory space

20

In [22]:
a.itemsize

4

In [23]:
len(a) 

5

In [24]:
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [25]:
a = np.logspace(1,10,20)
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [27]:
np.full(10,'a')

array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [28]:
np.full(10,40)

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [40]:
a.ndim


1

### 2-d array:

In [41]:
np.full((1,2),10)

array([[10, 10]])

In [43]:
b = np.array([[1,2,3,5],[6,7,8,9],[5,6,7,9]])
b

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [5, 6, 7, 9]])

In [44]:
b.ndim

2

In [45]:
b.nbytes

48

In [46]:
b.itemsize

4

In [47]:
len(b)

3

In [48]:
b.size

12

### 3-d array

In [50]:
c = np.array([[[1,2,34,5],[6,7,8,9]],[[3,4,5,6],[6,7,8,9]]])
c

array([[[ 1,  2, 34,  5],
        [ 6,  7,  8,  9]],

       [[ 3,  4,  5,  6],
        [ 6,  7,  8,  9]]])

In [51]:
c.ndim

3

In [52]:
len(c)

2

In [53]:
c.size

16

### Multidimensional array:

In [58]:
d = np.array([[1,2,3,4],[3,4,5,6]],ndmin = 20)
d

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                         [3, 4, 5, 6]]]]]]]]]]]]]]]]]]]])

In [59]:
d.ndim

20

### Accessing of elements from the array:

##### 1-d accessing:

In [62]:
a = np.array([1,2,3,5,7,89])
a

array([ 1,  2,  3,  5,  7, 89])

In [63]:
a[0]

1

In [64]:
a[-1]

89

In [65]:
a[:3]

array([1, 2, 3])

In [66]:
a[-3:]

array([ 5,  7, 89])

#### 2-d :

In [67]:
b

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [5, 6, 7, 9]])

In [69]:
b[0]

array([1, 2, 3, 5])

In [70]:
b[-1]

array([5, 6, 7, 9])

In [71]:
b[0,-1]

5

In [72]:
b[2,-2]

7

In [73]:
b[1:,-1]

array([9, 9])

In [74]:
b[:,-2:]

array([[3, 5],
       [8, 9],
       [7, 9]])

#### 3-d :

In [78]:
c

array([[[ 1,  2, 34,  5],
        [ 6,  7,  8,  9]],

       [[ 3,  4,  5,  6],
        [ 6,  7,  8,  9]]])

In [76]:
c[0]

array([[ 1,  2, 34,  5],
       [ 6,  7,  8,  9]])

In [77]:
c[0,0]

array([ 1,  2, 34,  5])

In [79]:
c[0,0,-2]

34

In [80]:
c[:,0]

array([[ 1,  2, 34,  5],
       [ 3,  4,  5,  6]])

In [81]:
c[:,:,-2]

array([[34,  8],
       [ 5,  8]])

### shape of the arrays:

In [82]:
a

array([ 1,  2,  3,  5,  7, 89])

In [83]:
a.shape

(6,)

In [84]:
b

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [5, 6, 7, 9]])

In [85]:
b.shape

(3, 4)

In [86]:
c

array([[[ 1,  2, 34,  5],
        [ 6,  7,  8,  9]],

       [[ 3,  4,  5,  6],
        [ 6,  7,  8,  9]]])

In [87]:
c.shape

(2, 2, 4)

### Reshaping of arrays:


* Changing the shape of the array and giving the new structure,

In [89]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
### 1-d array to 2-d array:

b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
b = a.reshape(1,9)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [96]:
b = a.reshape(9,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [98]:
### 1-d to 3-d array:

c = a.reshape(3,1,3)
c

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [105]:
c = a.reshape(3,3,1)

In [106]:
c

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [107]:
d = a.reshape(3,1,3,1)

In [108]:
d

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]],


       [[[7],
         [8],
         [9]]]])

In [109]:
a.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [111]:
a.reshape(-1,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

### Iteration of arrays:

In [112]:
l = [1,2,3,5]
l

[1, 2, 3, 5]

In [113]:
for i in l:
    print(i,end = " ")

1 2 3 5 

In [114]:
### 1-d array:

a 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

In [117]:
### 2-d array:

b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
for i in b:
    for j in i:
        print(j,end = " ")

1 2 3 4 5 6 7 8 9 

In [119]:
### 3-d array:

c = a.reshape(3,1,3)
c

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [120]:
for i in c:
    for j in i:
        for k in j:
            print(k,end =" ")

1 2 3 4 5 6 7 8 9 

In [122]:
### method for iterating array elements in numpy:

### nditer:

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

In [123]:
for i in np.nditer(b):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

### Joining of arrays:

In [126]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
b = np.arange(11,20).reshape(3,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [130]:
c = np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### stastical and Mathematical operations on arrays:

In [131]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
np.min(a)

1

In [133]:
np.max(a)

9

In [134]:
np.argmax(a)

8

In [135]:
np.argmin(a)

0

In [136]:
a.mean()

5.0

In [138]:
np.average(a)

5.0

In [140]:
np.median(a)

5.0

In [141]:
np.var(a)

6.666666666666667

In [142]:
np.std(a)

2.581988897471611

In [143]:
np.sum(a)

45

In [144]:
np.min(a,1)   ### 1 --- refers to row

         ### 0 ---  refers to column

array([1, 4, 7])

In [145]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.min(a,0)

array([1, 2, 3])

In [147]:
np.argmin(a,1)

array([0, 0, 0], dtype=int64)

In [148]:
np.argmax(a,0)

array([2, 2, 2], dtype=int64)

In [149]:
np.std(a,1)

array([0.81649658, 0.81649658, 0.81649658])

In [150]:
np.var(a,1)

array([0.66666667, 0.66666667, 0.66666667])

In [151]:
np.mean(a,0)

array([4., 5., 6.])

### stacking:

* organising/arranging in an order.
    * vertical stacking
    * Horizantal stacking
    

In [152]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
np.hstack(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [156]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [157]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [158]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [159]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [160]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [161]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [162]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [163]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [164]:
np.log2(a)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [165]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [166]:
np.remainder(a,4)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [167]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854],
       [229.18311805, 286.47889757, 343.77467708],
       [401.07045659, 458.3662361 , 515.66201562]])

In [168]:
np.diff(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [169]:
np.ediff1d(a)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [171]:
np.i0(a)   ### bessel function

array([[   1,    2,    4],
       [  11,   27,   67],
       [ 168,  427, 1093]])

In [172]:
np.mod(a,4)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [173]:
np.power(a,4)

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]], dtype=int32)

In [175]:
np.reciprocal(a,dtype = float)

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [176]:
np.multiply(a,2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [177]:
np.divide(a,4)

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [178]:
c = np.array([1+2j,3+5j,6+4j])
c

array([1.+2.j, 3.+5.j, 6.+4.j])

In [179]:
c.dtype

dtype('complex128')

In [181]:
np.real(c)

array([1., 3., 6.])

In [184]:
np.imag(c)

array([2., 5., 4.])

### Ravel and Flatten:

In [185]:
original = np.array([1,2,3,5,6])


In [186]:
### ravel:

copyr = original.ravel()
copyr

array([1, 2, 3, 5, 6])

In [187]:
copyr[0] = 10

In [188]:
copyr

array([10,  2,  3,  5,  6])

In [189]:
original

array([10,  2,  3,  5,  6])

In [190]:
### Flatten:

copyf = original.flatten()
copyf

array([10,  2,  3,  5,  6])

In [191]:
copyf[0] = 1

In [192]:
copyf

array([1, 2, 3, 5, 6])

In [193]:
original

array([10,  2,  3,  5,  6])

In [194]:
a = np.array([1,2,3,4,5,7,4,6,8,9,11,12])
a



array([ 1,  2,  3,  4,  5,  7,  4,  6,  8,  9, 11, 12])

In [195]:
len(a)

12

In [196]:
a.reshape(3,2,2)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  7],
        [ 4,  6]],

       [[ 8,  9],
        [11, 12]]])

In [197]:
a.reshape(2,2,3,1)

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 7]]],


       [[[ 4],
         [ 6],
         [ 8]],

        [[ 9],
         [11],
         [12]]]])

In [198]:
a.reshape(2,2,3,1,1)

array([[[[[ 1]],

         [[ 2]],

         [[ 3]]],


        [[[ 4]],

         [[ 5]],

         [[ 7]]]],



       [[[[ 4]],

         [[ 6]],

         [[ 8]]],


        [[[ 9]],

         [[11]],

         [[12]]]]])